name: AzPSFuncReuse
on: [workflow_dispatch]
jobs:

  Resources:
    runs-on: ubuntu-latest  
    steps:   
    - uses: actions/checkout@v4    
    - name: Use Function
      run: |
        . ./GHActionTest/FuncVar.ps1
        Get-CurrentTime
      shell: pwsh  

#Combining these two — the dot sourcing operator and the relative path to the script — with a space in between (. ./filename.ps1) 
#instructs PowerShell to execute the filename.ps1 script in the current scope, making any functions, variables, etc., defined in the file
#.. immediately available in the current PowerShell session or script.      