name: AzPSFuncVarReuse
on: [workflow_dispatch]
jobs:

  Resources:
    runs-on: ubuntu-latest  
    steps:   
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: Run Azure PowerShell Script File
      uses: azure/powershell@v2
      with:
        inlineScript: ./3TierApp/FuncVar.ps1
        azPSVersion: 'latest'
    
    - name: Use RG Name
      run: |
        $rgName = "${{ env.RG_NAME }}"
        Write-Host "Using Resource Group Name: $rgName"
      shell: pwsh