name: AzurePowerShellScript
on: [workflow_dispatch]
jobs:

  Resources:
    runs-on: ubuntu-latest  #Windows has the RM modules along with Az. 'ubuntu-latest' works. But both have 2 versions older modules. 11.3 instead of 11.5.
    container: mcr.microsoft.com/azure-powershell:latest  # azure/login@v2 fails to run inside the container.

    steps:
    - name: Check Out
      uses: actions/checkout@v4                      #with:      #Checkout presents the repo to the Pipeline execution runtime.
      with:
        sparse-checkout-cone-mode:  false           #This excludes the files in root of the repo from being checked out.
        sparse-checkout: |                          #This presents the files in the root of the repo and the folder
          GHActionTest/                             
          3TierApp/                 

    - name: Run Azure PowerShell Script File
      shell: pwsh
      run: |
          . ./3TierApp/HelperFunctions.ps1 
          Connect-MySubscription ${{ vars.MULLICKTENANTID }} ${{ vars.FTESUBID }} ${{ vars.PSGHACTIONSCLIENTID }} ${{ secrets.PSGHACTIONSSECRET }}
          Get-ChildItem -Recurse
            
#This only shows the checked out repo folders. However, in another workflow, calling even a non checked out folder item worked
      
    - name: TestStep
      shell: pwsh
      run: |
        ./GHActionTest/GetRG.ps1


#2nd job triggers in parallel.         