name: AzurePowerShellScript
on: [workflow_dispatch]
jobs:

  Resources:
    runs-on: ubuntu-latest  #Windows has the RM modules along with Az. 'ubuntu-latest' works. But both have 2 versions older modules. 11.3 instead of 11.5.
    #container:  #Azure login fails to run inside the container.
     #   image: mcr.microsoft.com/azure-powershell:latest
    steps:
    
    - name: Check Out
      uses: actions/checkout@v4                      #with:      #Checkout presents the repo to the Pipeline execution runtime.
      with:
        sparse-checkout: GHActionTest/ 3TierApp/             #This presents the file in the root of the repo and the folder
       

    - name: Login Azure
      uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true                      #Without session login isn't shared across steps

    - name: Run Azure PowerShell Script File
      uses: azure/powershell@v2
      with:
        inlineScript: Get-ChildItem -Recurse
        azPSVersion: 'latest'
    
    - name: TestStep
      uses: azure/powershell@v2
      with:
        inlineScript: ./GHActionTest/GetRG.ps1
        azPSVersion: 'latest'

#2nd job triggers in parallel.         