name: AzurePowerShellScript2
on: [workflow_dispatch]
jobs:

  Resources:
    runs-on: ubuntu-latest  
    steps:   
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: Run Azure PowerShell Script File
      uses: azure/powershell@v2
      with:
        inlineScript: ./3TierApp/GovResource.ps1
        azPSVersion: 'latest'
    
    - name: TestStep
      uses: azure/powershell@v2
      with:
        inlineScript: ./3TierApp/GetRG.ps1
        azPSVersion: 'latest'
     