name: AzPSImageInfraDeploymentWithApproval
on: [workflow_dispatch]

jobs:
  GovernanceResourcesJob:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-powershell:latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Governance resources
        shell: pwsh
        run: . ./3TierApp/HelperFunctions.ps1 
            Connect-AzAccount -ServicePrincipal -Tenant ${{ vars.MULLICKTENANTID }} -Subscription ${{ vars.FTESUBID }} -ClientId ${{ vars.PSGHACTIONSCLIENTID }} -SPNPswd ${{ secrets.PSGHACTIONSSECRET }}
            ./3TierApp/GovResource.ps1

  DeployVirtualMachines:
    needs: GovernanceResourcesJob
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-powershell:latest
    environment: 
      name: VMEnvironment  # This environment has manual approval configured
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Virtual machines
        shell: pwsh
        run: . ./3TierApp/HelperFunctions.ps1 
             Connect-AzAccount -ServicePrincipal -Tenant ${{ vars.MULLICKTENANTID }} -Subscription ${{ vars.FTESUBID }} -ClientId ${{ vars.PSGHACTIONSCLIENTID }} -SPNPswd ${{ secrets.PSGHACTIONSSECRET }} 
             ./GHActionTest/GetRG.ps1
