name: AzPSInfraDeploymentWithApproval
on: [workflow_dispatch]

jobs:
  AzInfraDeployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy Governance resources
        uses: azure/powershell@v2
        with:
          inlineScript: |
            . ./3TierApp/HelperFunctions.ps1
            ./3TierApp/GovResource.ps1
          azPSVersion: 'latest'

      # Environment for manual approval
      - name: Manual Approval
        if: github.ref == 'refs/heads/main'  # Conditional to only require approval on main branch
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'AzPSInfraDeployment.yml',
              ref: 'main',
            })
        environment:
          name: VMEnvironment  # Name of the environment requiring approval
          url: ${{ steps.deploy.outputs.deployment-url }}  # Optional: Provide a URL to the deployment

      - name: Deploy Virtual machines
        uses: azure/powershell@v2
        with:
          inlineScript: ./GHActionTest/GetRG.ps1
          azPSVersion: 'latest'
