name: AzPSInfraDeployment
on: [workflow_dispatch]
jobs:

  AzInfraDeployment:
    runs-on: ubuntu-latest  
    steps:   
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: Deploy Governance resources
      uses: azure/powershell@v2
      with:
        inlineScript: ./3TierApp/GovResource.ps1
        azPSVersion: 'latest'
    
    - name: Deploy Virtual machines
      uses: azure/powershell@v2
      with:
        inlineScript: ./3TierApp/GetRG.ps1
        azPSVersion: 'latest'
     