name: AzPSInfraDeploymentWithApproval
on: [workflow_dispatch]

jobs:
  GovernanceResourcesJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy Governance resources
        uses: azure/powershell@v2
        with:
          inlineScript: |
            . ./3TierApp/HelperFunctions.ps1
            ./3TierApp/GovResource.ps1
          azPSVersion: 'latest'

  DeployVirtualMachines:
    needs: GovernanceResourcesJob
    runs-on: ubuntu-latest
    environment: 
      name: VMEnvironment  # This environment should have manual approval configured
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy Virtual machines
        uses: azure/powershell@v2
        with:
          inlineScript: ./GHActionTest/GetRG.ps1
          azPSVersion: 'latest'
