name: AzPSInfraDeploymentWithApproval
on: [workflow_dispatch]

jobs:
  AzInfraDeployment:
    runs-on: ubuntu-latest
    environment: VMEnvironment  # Reference the environment here
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy Governance resources
        uses: azure/powershell@v2
        with:
          inlineScript: |
            . ./3TierApp/HelperFunctions.ps1
            ./3TierApp/GovResource.ps1
          azPSVersion: 'latest'

      # The deployment step now waits for an approval if the environment requires it
      - name: Deploy Virtual machines
        uses: azure/powershell@v2
        with:
          inlineScript: ./GHActionTest/GetRG.ps1
          azPSVersion: 'latest'
