name: Run PowerShell Script

on:
  push:
    branches:
      - main  # Adjust as needed
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-powershell:
    runs-on: windows-latest

    steps:
      - name: Run Get-Process
        run: pwsh -command "Get-Process"
