name: WfContJobEnvVarReuse
on: [workflow_dispatch]

jobs:
  set-env-variable:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-powershell:latest
    outputs:
      rg_name: ${{ steps.set-env.outputs.rg_name }}
    steps:
      - uses: azure/login@v2
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}  
            enable-AzPSSession: true

      - name: Set RG_NAME environment variable
        id: set-env
        uses: azure/powershell@v2
        with:
            azPSVersion: 'latest'
            inlineScript: |
                $RG_NAME = (Get-AzResourceGroup -Name GitHubAction24).ResourceGroupName
                Write-Output "::set-output name=rg_name::$RG_NAME"
                Get-Content -Path $Env:GITHUB_ENV
                Get-ChildItem env:

  use-env-variable:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-powershell:latest
    needs: set-env-variable
    steps:
      - name: Use RG_NAME in Azure PowerShell
        shell: pwsh
        run: |
            $RG_NAME = '${{ needs.set-env-variable.outputs.rg_name }}'
            Write-Output "Using resource group: $RG_NAME"
