name: WfContJobEnvVarReuse
on: [workflow_dispatch]

jobs:
  set-env-variable:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-powershell:latest
    outputs:
      rg_name: ${{ steps.set-env.outputs.rg_name }}
    steps:
      - name: Set RG_NAME environment variable
        id: set-env
        shell: pwsh
        run: |
            $RG_NAME = "GitHubAction24"
            Write-Output "::set-output name=rg_name::$RG_NAME"

  use-env-variable:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-powershell:latest
    needs: set-env-variable
    steps:
      - name: Use RG_NAME in Azure PowerShell
        shell: pwsh
        run: |
            $RG_NAME = '${{ needs.set-env-variable.outputs.rg_name }}'
            Write-Output "Using resource group: $RG_NAME"
